### ISSUE TITLE
Light mode settings not being applied to Dock Area tabs in version 0.4.0

### ISSUE THREAD

**Issue by kahwait** [Adanos020/egui_dock#108] opened 2023-02-25 22:53 UTC
**Describe the bug**
Some light mode style settings from egui are not being set in egui_dock::Style. This is very noticeable in the tab bar background colour with the colour being permanently in dark mode. 
This behaviour is not present in release 0.3

**To Reproduce**
1. Update to egui_dock 0.4.0 and egui to 0.21
2. Choose any of the demos in the repo
3. Modify the demo to set the visuals to light mode 
4. Observer the tab background colour is set to dark mode

**Expected behavior**
In light mode, the tab background colour should be be in light mode

**Screenshots**
![egui_dock_tab_stuck_in_dark_mode](https://user-images.githubusercontent.com/6728605/221383062-1ab98887-f2f4-4c93-a044-6a74ab557775.png)

**Additional context**
The tab_bar_background_color and separator_color_hovered fields differ when compared against style settings from version 0.3
![egui_dock_style_diff](https://user-images.githubusercontent.com/6728605/221383076-ee7154fa-ec6c-41ed-9c92-25d53b07b147.png)

**Comment by lvaroqui** [comment] 2023-02-26 12:53
I could not reproduce the issue on Linux using this diff:

```
diff --git a/examples/text_editor.rs b/examples/text_editor.rs
index 932d036..a2d2925 100644
--- a/examples/text_editor.rs
+++ b/examples/text_editor.rs
@@ -64,6 +64,8 @@ impl Default for MyApp {
 
 impl eframe::App for MyApp {
     fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
+        ctx.set_visuals(egui::Visuals::light());
+
```

Could you share what you did on your side?

**Comment by kahwait** [comment] 2023-02-26 22:35
That's exactly the change I did on my end.  I created a new cargo project and copied text_editor.rs  into the bin folder. Cargo.toml contains only these dependencies
```
[dependencies]
eframe = "0.21"
egui = "0.21"
egui_dock = "0.4"
```
`cargo run --bin text_editor `

Interestingly enough if I clone the repo and run the modified example via `cargo run --example text_editor`
, I don't see the issue but I do see it when running the bin project

![text_editor_egui_dock](https://user-images.githubusercontent.com/6728605/221441192-6d986587-b48d-4e9f-b355-4f15e95b0b59.png)

I'm running on Ubuntu 20.04.5 but witnessed the same issue on Windows 10 too.

**Comment by lvaroqui** [comment] 2023-03-04 10:37
Actually this seems to be fixed on main branch with this commit: 528b89245928d055dabb00cd9001c22d275f789b

**Comment by lvaroqui** [comment] 2023-03-12 13:07
@Adanos020 maybe we could make a patch release to fix this?

**Comment by Adanos020** [comment] 2023-03-12 18:43
@kahwait Yeah, not a bad idea

**Closed** 2023-03-14 13:11 UTC
Labels: bug
