### ISSUE TITLE
Nesting DockArea in another DockArea produces weird results

### ISSUE THREAD

**Issue by thatbakamono** [Adanos020/egui_dock#52] opened 2022-10-12 19:33 UTC
While it looks correct
![image](https://user-images.githubusercontent.com/13699966/195430693-403ed39f-55e8-4494-b9e5-65c0a34a1281.png)
clicking on `Linear` or `Tree` doesn't really do anything, it kinda behaves like moving but almost immediately stops. `Chunks`, `Viewport` and `Properties` work as regular.

Also, things stop being rendered once you put the second `DockArea` in a `TopBottomPanel`
![image](https://user-images.githubusercontent.com/13699966/195431388-75e9ccfb-daf3-4081-a8ea-4cdce020a1cd.png)

My code:
```rs
use eframe::{
    egui::{menu, Context, TopBottomPanel, Ui, WidgetText},
    App, Frame, NativeOptions,
};
use egui_dock::{DockArea, NodeIndex, TabViewer, Tree};

fn main() {
    eframe::run_native(
        "BSP Editor",
        NativeOptions::default(),
        Box::new(|_| Box::new(BspEditor::new())),
    );
}

#[derive(Debug, Eq, PartialEq)]
enum ChunkTab {
    Linear,
    Tree,
}

struct ChunkTabs;

impl TabViewer for ChunkTabs {
    type Tab = ChunkTab;

    fn ui(&mut self, _ui: &mut Ui, tab: &mut Self::Tab) {
        match *tab {
            ChunkTab::Linear => {
                _ui.label("Linear");
                _ui.button("Linear");
            }
            ChunkTab::Tree => {
                _ui.label("Tree");
                _ui.button("Tree");
            }
        }
    }

    fn title(&mut self, tab: &mut Self::Tab) -> WidgetText {
        match *tab {
            ChunkTab::Linear => "Linear",
            ChunkTab::Tree => "Tree",
        }
        .into()
    }    
}

#[derive(Debug, Eq, PartialEq)]
enum Tab {
    Chunks,
    Viewport,
    Properties,
}

struct Tabs {
    tree: Tree<ChunkTab>,
}

impl Tabs {
    fn new() -> Self {
        Self {
            tree: Tree::new(vec![ChunkTab::Linear, ChunkTab::Tree]),
        }
    }
}

impl TabViewer for Tabs {
    type Tab = Tab;

    fn ui(&mut self, ui: &mut Ui, tab: &mut Self::Tab) {
        match *tab {
            Tab::Chunks => {
                TopBottomPanel::bottom("chunks").show_inside(ui, |ui| {
                    DockArea::new(&mut self.tree).show_inside(ui, &mut ChunkTabs);
                });
            }
            Tab::Viewport => {}
            Tab::Properties => {}
        }
    }

    fn title(&mut self, tab: &mut Self::Tab) -> WidgetText {
        match *tab {
            Tab::Chunks => "Chunks",
            Tab::Viewport => "Viewport",
            Tab::Properties => "Properties",
        }
        .into()
    }
}

struct BspEditor {
    tree: Tree<Tab>,
}

impl BspEditor {
    fn new() -> Self {
        let mut tree = Tree::new(vec![Tab::Chunks]);

        let [_tree_panel, viewport_panel] =
            tree.split_right(NodeIndex::root(), 0.25, vec![Tab::Viewport]);

        tree.split_right(viewport_panel, 0.66, vec![Tab::Properties]);

        Self { tree }
    }
}

impl App for BspEditor {
    fn update(&mut self, context: &Context, _frame: &mut Frame) {
        TopBottomPanel::top("menu").show(context, |ui| {
            menu::bar(ui, |ui| {
                ui.menu_button("File", |ui| {
                    if ui.button("New").clicked() {
                        todo!();
                    }

                    if ui.button("Open").clicked() {
                        todo!();
                    }

                    if ui.button("Save").clicked() {
                        todo!();
                    }

                    if ui.button("Save as").clicked() {
                        todo!();
                    }
                });
            });
        });

        DockArea::new(&mut self.tree).show(context, &mut Tabs::new());
    }
}
```

**Comment by lvaroqui** [comment] 2023-03-25 19:03
This is not a bug in egui_dock but in your code!

You create a new `Tabs` instance every frame in your `update` function:

```rust
DockArea::new(&mut self.tree).show(context, &mut Tabs::new());
```

Instead you should store the tabs into your `BspEditor` and pass it to the show method like so:

```rust
struct BspEditor {
    tree: Tree<Tab>,
    tabs: Tabs,
}

// ...

DockArea::new(&mut self.tree).show(context, &mut self.tabs);
```

One side note though, each DockArea must have a different id, you can provide a custom id like this:

```rust
Tab::Chunks => {
    DockArea::new(&mut self.tree)
        .id("other".into())
        .show_inside(ui, &mut ChunkTabs);
}
```

Full corrected code for reference:

```rust
use eframe::{
    egui::{menu, Context, TopBottomPanel, Ui, WidgetText},
    App, Frame, NativeOptions,
};
use egui_dock::{DockArea, NodeIndex, TabViewer, Tree};

fn main() {
    eframe::run_native(
        "BSP Editor",
        NativeOptions::default(),
        Box::new(|_| Box::new(BspEditor::new())),
    )
    .unwrap();
}

#[derive(Debug, Eq, PartialEq)]
enum ChunkTab {
    Linear,
    Tree,
}

struct ChunkTabs;

impl TabViewer for ChunkTabs {
    type Tab = ChunkTab;

    fn ui(&mut self, ui: &mut Ui, tab: &mut Self::Tab) {
        match *tab {
            ChunkTab::Linear => {
                ui.label("Linear");
            }
            ChunkTab::Tree => {
                ui.label("Tree");
            }
        }
    }

    fn title(&mut self, tab: &mut Self::Tab) -> WidgetText {
        match *tab {
            ChunkTab::Linear => "Linear",
            ChunkTab::Tree => "Tree",
        }
        .into()
    }
}

#[derive(Debug, Eq, PartialEq)]
enum Tab {
    Chunks,
    Viewport,
    Properties,
}

struct Tabs {
    tree: Tree<ChunkTab>,
}

impl Tabs {
    fn new() -> Self {
        Self {
            tree: Tree::new(vec![ChunkTab::Linear, ChunkTab::Tree]),
        }
    }
}

impl TabViewer for Tabs {
    type Tab = Tab;

    fn ui(&mut self, ui: &mut Ui, tab: &mut Self::Tab) {
        match *tab {
            Tab::Chunks => {
                DockArea::new(&mut self.tree)
                    .id("other".into())
                    .show_inside(ui, &mut ChunkTabs);
            }
            Tab::Viewport => {}
            Tab::Properties => {}
        }
    }

    fn title(&mut self, tab: &mut Self::Tab) -> WidgetText {
        match *tab {
            Tab::Chunks => "Chunks",
            Tab::Viewport => "Viewport",
            Tab::Properties => "Properties",
        }
        .into()
    }
}

struct BspEditor {
    tree: Tree<Tab>,
    tabs: Tabs,
}

impl BspEditor {
    fn new() -> Self {
        let mut tree = Tree::new(vec![Tab::Chunks]);

        let [_tree_panel, viewport_panel] =
            tree.split_right(NodeIndex::root(), 0.25, vec![Tab::Viewport]);

        tree.split_right(viewport_panel, 0.66, vec![Tab::Properties]);

        Self {
            tree,
            tabs: Tabs::new(),
        }
    }
}

impl App for BspEditor {
    fn update(&mut self, context: &Context, _frame: &mut Frame) {
        TopBottomPanel::top("menu").show(context, |ui| {
            menu::bar(ui, |ui| {
                ui.menu_button("File", |ui| {
                    if ui.button("New").clicked() {
                        todo!();
                    }

                    if ui.button("Open").clicked() {
                        todo!();
                    }

                    if ui.button("Save").clicked() {
                        todo!();
                    }

                    if ui.button("Save as").clicked() {
                        todo!();
                    }
                });
            });
        });

        DockArea::new(&mut self.tree).show(context, &mut self.tabs);
    }
}
```

**Comment by lvaroqui** [comment] 2023-03-25 19:03
@Adanos020 this is not a bug, we can close the issue :slightly_smiling_face:

**Comment by Adanos020** [comment] 2023-03-25 19:27
@lvaroqui Smashing, this makes a lot of sense. Thanks for investigating this!

**Closed by Adanos020** 2023-03-25 19:27 UTC
Labels: bug
