### ISSUE TITLE
Style.separator.interact_size

### ISSUE THREAD

**Issue by gre-v-el** [Adanos020/egui_dock#127] opened 2023-05-17 16:36 UTC
For me it is always difficult to resize the layout when the separator width is set to 1px (default). I feel the most comfortable when it set to about 10px-15px, but then the ui looks ugly.

A new field, Style.separator.interact_size could represent the logical thickness of a separator and would not affect the graphical thickness (Style.separator.width).

**Comment by lvaroqui** [comment] 2023-05-19 18:02
Duplicate of #125!

**Comment by Adanos020** [comment] 2023-05-20 17:47
Closed by #128

**Closed by Adanos020** 2023-05-20 17:47 UTC
Labels: enhancement
