### ISSUE TITLE
hello example crash

### ISSUE THREAD

**Issue by skydig** [Adanos020/egui_dock#205] opened 2023-11-30 03:10 UTC
**Describe the bug**
as title
**To Reproduce**

cargo run --example hello
make gui like following picture,then click view->File Browser, then hello app will crash
....\egui_dock\src\widgets\dock_area\show\window_surface.rs:74:21:
internal error: entered unreachable code: a window surface should never be empty

![image](https://github.com/Adanos020/egui_dock/assets/27293515/33c539b3-d19f-4874-b9fe-c1d248250f42)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Adanos020** [comment] 2023-12-10 20:23
Closing this as a duplicate of #206

**Closed by Adanos020** 2023-12-10 20:23 UTC
Labels: bug, duplicate
