### ISSUE TITLE
DockArea inside a Window can cause it to grow indefinitely

### ISSUE THREAD

**Issue by Kryptos-FR** [Adanos020/egui_dock#90] opened 2023-01-04 14:07 UTC
```toml
egui = "0.20"
egui_dock = "0.3.1"
```

**Describe the bug**
When splitting horizontally (e.g. moving a tab below another), the height of the containing window will grow forever.

**To Reproduce**
1. Open the simple example, and modify the code as follow:
```rust
impl eframe::App for MyApp {
  fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
    Window::new("Hello")
      .show(ctx, |ui| {
        DockArea::new(&mut self.tree)
          .style(Style::from_egui(ctx.style().as_ref()))
          .show_inside(ui, &mut TabViewer {});
      });
  }
}
```
2. Run the example: `cargo run --example simple`.

**Expected behavior**
Splitting should divide in areas half of the original height without causing a resizing.

**Screenshots**
![window_issue2](https://user-images.githubusercontent.com/3006525/210571966-25caa2e1-4f37-429d-84bc-372f32ed91a1.gif)

**Additional context**
This doesn't happen when the `DockArea` is contained within a Panel (e.g. `CentralPanel`), a `ScrollArea`, etc.
I believe it is somehow causes by calculating the split based on percentage/ratio of the available size.

It's also fine if the `Window` size is fixed. However since Window doesn't have a `max_height`, there is no upper bound, when resizing is allowed.

**Comment by Adanos020** [comment] 2023-01-22 20:51
Sorry for the late reply.

In your GIF it's visible that part of the tab bar isn't being drawn below the window decoration but slightly above its bottom border. Might it be that this little area adds to the "available" size?

**Comment by lvaroqui** [comment] 2023-02-05 10:22
I cannot reproduce this error on Linux (Manjaro), I'll have to try on Windows. @Adanos020, the decoration also sticks out on the window decoration but it does not seem to cause a problem on my side.

**Comment by Kryptos-FR** [comment] 2023-02-06 12:13
I also couldn't reproduce on `WSL Ubuntu 22.04.1 LTS`. So I guess it is a Windows issue.

**Comment by Aceeri** [comment] 2023-02-08 00:07
This doesn't seem to be a windows issue as I can't repro either

**Comment by Kryptos-FR** [comment] 2023-02-08 08:17
Did you move the mouse? The growing only happens when the UI receives mouse events (I guess because it triggers a redraw).

I can reproduce on two different Windows machine (10 & 11) with rust stable or rust nightly.

Additional note: screens have high DPI (150 %) in case it matters.

**Comment by white-axe** [comment] 2023-11-04 17:40
I can confirm this issue is present in egui_dock 0.7.3 and 0.8.2 when using the given example and modifications, but it only happens when I drag around tabs and only when there are no splits in the main dock area. Here's a video with 0.8.2:

![Screen recording](https://github.com/Adanos020/egui_dock/assets/144272066/426505f0-4d1d-47f7-b257-980971b73bd5)

There are no issues for me with egui_dock versions older than 0.7.

I'm using GNOME 45 on Wayland.

**Comment by Adanos020** [comment] 2023-11-05 00:32
@white-axe Thanks for confirming, we shall look into this again. We didn't have a consistent repro method before, and the one you posted seems perfect.

**Comment by Adanos020** [comment] 2024-04-03 19:15
Hello again, I think this issue should now be resolved by [this commit](https://github.com/Adanos020/egui_dock/commit/01bb07c3287861dbc801c5ce3d48ebad588f4bd5). I'm going to release it soon in 0.12.

@white-axe I would really appreciate it if you could verify the fix again! I have already tested it in the modified `simple` example and it seems to work as it should. :smiley:

**Comment by white-axe** [comment] 2024-04-03 21:27
Yup, seems to be fixed now

**Comment by Adanos020** [comment] 2024-04-03 22:10
Great stuff, thank you! I'll close this then.

**Closed by Adanos020** 2024-04-03 22:10 UTC
Labels: bug
